// events
// actions
export const ACTION_FETCH_EVENTS = 'ACTION_FETCH_EVENTS';
export const ACTION_FILTER_EVENTS = 'ACTION_FILTER_EVENTS';

// mutations
export const MUTATION_UPDATE_EVENTS = 'MUTATION_UPDATE_EVENTS';
export const MUTATION_FILTRED_EVENTS = 'MUTATION_FILTRED_LIST';
export const MUTATION_UPDATE_FILTERS = 'MUTATION_UPDATE_FILTERS';

// player
export const ACTION_FETCH_PLAYER = 'ACTION_FETCH_PLAYER';
export const MUTATION_SET_PLAYER = 'MUTATION_SET_PLAYER';

// auth
export const ACTION_LOGIN = 'ACTION_LOGIN';
export const MUTATION_LOGIN = 'MUTATION_LOGIN';
export const MUTATION_LOGOUT = 'MUTATION_LOGOUT';
